projectName: Governance Frameworks
jsonFilePath: ./input.json
baseUrl: https://uno.ai
portalHeading: Uno.ai - GRC Glossary
portalDescription: Explore the most sophisticated Gen AI GRC Autonomous Agent Platform.
portalTitle: Governance Frameworks - AI GRC Solutions
searchPlaceholder: Search for GRC solutions...
useAlphabetsCategory: true
homeLink: https://uno.ai/
logoLink: https://uno.ai/
ctaText: Get Started
aboutLink: https://uno.ai/about
productsLink: https://uno.ai/products
logoImgUrl: https://uno.ai/assets/img/uno/unoaiinvert.png
ctaLink: https://uno.ai/get-started
copyrightText: © 2023 Uno.ai. All rights reserved.
faviconUrl: https://uno.ai/favicon.ico
googleTagManagerId: GTM-XXXXXX
pagesTitle:
  prefix: ''
  suffix: ''
categoryPagesTitle:
  prefix: ''
  suffix: ''
templateRoot:
  - ./templates
  - ./templates
homeTemplatePath: ./templates/homePageTemplate.ejs
categoryTemplatePath: ./templates/categoryTemplate.ejs
pageTemplatePath: ./templates/pagesTemplate.ejs
outputDir: ./output
socialLinks:
  - platform: Twitter
    url: https://twitter.com/unoai
  - platform: LinkedIn
    url: https://www.linkedin.com/company/uno-ai
  - platform: Facebook
    url: https://www.facebook.com/unoai
theme:
  primaryColor: '#0056b3'
  secondaryColor: '#f8f9fa'
  backgroundColor: '#ffffff'
  textColor: '#212529'
  accentColor: '#ffc107'
fonts:
  - family: Roboto
    weights:
      - 400
      - 500
      - 600
  - family: Open Sans
    weights:
      - 500
      - 600
      - 700
