projectName: Governance Frameworks
jsonFilePath: ./input.json
baseUrl: https://uno.ai
portalHeading: Governance Frameworks Portal
portalDescription: >-
  World's most sophisticated Gen AI GRC copilot and autonomous agent platform,
  transforming GRC from legacy to AI.
portalTitle: Governance Frameworks - AI GRC Solutions
searchPlaceholder: Search for AI GRC solutions...
useAlphabetsCategory: true
homeLink: https://uno.ai/
logoLink: https://uno.ai/
ctaText: Get Started
aboutLink: https://uno.ai/about
productsLink: https://uno.ai/products
logoImgUrl: https://uno.ai/logo.png
ctaLink: https://uno.ai/get-started
copyrightText: © 2023 Uno.ai. All rights reserved.
faviconUrl: https://uno.ai/favicon.ico
googleTagManagerId: ''
pagesTitle:
  prefix: ''
  suffix: ''
categoryPagesTitle:
  prefix: ''
  suffix: ''
templateRoot:
  - ./templates
  - ./templates
homeTemplatePath: ./templates/homePageTemplate.ejs
categoryTemplatePath: ./templates/categoryTemplate.ejs
pageTemplatePath: ./templates/pagesTemplate.ejs
outputDir: ./output
socialLinks:
  - platform: Twitter
    url: https://twitter.com/unoai
  - platform: LinkedIn
    url: https://linkedin.com/company/unoai
  - platform: Facebook
    url: https://facebook.com/unoai
theme:
  primaryColor: '#007BFF'
  secondaryColor: '#6c757d'
  backgroundColor: '#ffffff'
  textColor: '#212529'
  accentColor: '#FF5733'
fonts:
  - family: Helvetica, Arial, sans-serif
    weights:
      - 400
      - 500
      - 600
  - family: '''Roboto'', sans-serif'
    weights:
      - 500
      - 600
      - 700
